name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:

jobs:
  job1:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
        - name: run
          run: echo ${{ matrix.os }} > test.txt
        - name: upload
          uses: actions/upload-artifact@v4
          with:
            name: test_upload_${{ matrix.os }}
            path: test.txt
